package com.harsh.jarvis.ai

enum class IntentType {
    CREATE_REMINDER, OPEN_APP, SAVE_MEMORY, SEARCH_MEMORY, SHOW_TASKS, DELETE_TASK,
    SHOW_EVOLUTION, SHOW_EVOLUTION_XP, SHOW_EVOLUTION_QUESTS, COMPLETE_EVOLUTION_QUEST, SHOW_EVOLUTION_WEAKNESS, NEXT_EVOLUTION_CHALLENGE, START_EVOLUTION_CHALLENGE,
    CONFIRM_ACTION, CANCEL_ACTION, SHOW_HISTORY, RETRY_ACTION, HELP,
    CALENDAR_QUERY, CONTACT_LOOKUP, CREATE_ROUTINE, SHOW_PROFILE, SET_PROFILE,
    CONVERSATION,
    TODAY_BRIEFING, NEXT_BEST_ACTION, PLAN_DAY, SHOW_DEADLINES, SHOW_MISSING, SHOW_YESTERDAY_INCOMPLETE,
    SET_AVAILABILITY, REMIND_WHEN_FREE, SNOOZE_PROACTIVE, COMPLETE_PROACTIVE, BREAK_DOWN_TASK, EVENING_REVIEW, UNKNOWN
}
